"""
FastAPI inference endpoint — MIC Creep Prediction
==================================================
Serves predictions and pre-aggregated surveillance data.

Startup behaviour:
  - Dev  (MODEL_SOURCE=local): loads models/xgb_tuned.pkl from disk
  - Prod (MODEL_SOURCE=huggingface): downloads artefact from HF Hub
  - Pre-computed JSON data (reports/api_*.json) is loaded once at startup

Endpoints:
  GET  /health
  GET  /api/trend/mic90          historical + forecast MIC90 by year
  GET  /api/country-stats        resistance rate + MIC90 by country
  GET  /api/features/importance  top 20 SHAP features
  POST /api/predict              single-isolate MIC prediction

Run locally:
  .venv/bin/python -m uvicorn src.api.main:app --reload --port 8000
"""

import json
import os
from pathlib import Path
from typing import Optional

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
MODELS_DIR   = PROJECT_ROOT / "models"
REPORTS      = PROJECT_ROOT / "reports"

MODEL_SOURCE = os.getenv("MODEL_SOURCE", "local")
HF_REPO      = os.getenv("HF_MODEL_REPO", "")   # e.g. "yourname/mic-creep-kpneumoniae"

EUCAST_R  = 8.0
LOG2_R    = np.log2(EUCAST_R)

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="MIC Creep Prediction API",
    description=(
        "Predicts Minimum Inhibitory Concentration (MIC) drift for "
        "Klebsiella pneumoniae + Meropenem. "
        "Vivli AMR Surveillance Challenge 2026."
    ),
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# State loaded at startup
# ---------------------------------------------------------------------------

_model        = None
_feature_names: list[str] = []
_mic90_trend:  list[dict] = []
_country_stats: list[dict] = []
_shap_importance: list[dict] = []
_censoring_lookup: dict[int, float] = {}


@app.on_event("startup")
async def startup_event() -> None:
    global _model, _feature_names
    global _mic90_trend, _country_stats, _shap_importance, _censoring_lookup

    # Load model
    if MODEL_SOURCE == "huggingface" and HF_REPO:
        from huggingface_hub import hf_hub_download
        pkl_path = hf_hub_download(repo_id=HF_REPO, filename="xgb_tuned.pkl")
        json_path = hf_hub_download(repo_id=HF_REPO, filename="feature_names.json")
        _model = joblib.load(pkl_path)
        _feature_names = json.loads(Path(json_path).read_text())
    else:
        _model = joblib.load(MODELS_DIR / "xgb_tuned.pkl")
        _feature_names = json.loads((MODELS_DIR / "feature_names.json").read_text())

    # Load pre-aggregated data files (generated by 4_run_export.py)
    def _load(fname):
        p = REPORTS / fname
        return json.loads(p.read_text()) if p.exists() else []

    _mic90_trend      = _load("api_mic90_trend.json")
    _country_stats    = _load("api_country_stats.json")
    _shap_importance  = _load("api_shap_importance.json")
    raw_cens          = _load("api_censoring_lookup.json")
    _censoring_lookup = {int(float(k)): float(v) for k, v in raw_cens.items()} if isinstance(raw_cens, dict) else {}


# ---------------------------------------------------------------------------
# Request / response schemas
# ---------------------------------------------------------------------------

class PredictionRequest(BaseModel):
    year:          int   = Field(..., ge=2004, le=2030, description="Isolation year")
    country:       str   = Field(..., description="Country name (e.g. 'Ukraine')")
    sex:           str   = Field("Male", description="'Male' or 'Female'")
    age_group:     str   = Field("Adult", description="'Paediatric', 'Adult', or 'Elderly'")
    specimen_type: str   = Field("other", description="wound | blood | respiratory | urine | peritoneal | other")
    kpc_pos:       bool  = Field(False)
    ndm_pos:       bool  = Field(False)
    oxa_pos:       bool  = Field(False)
    vim_pos:       bool  = Field(False)
    imp_pos:       bool  = Field(False)
    ges_pos:       bool  = Field(False)


class PredictionResponse(BaseModel):
    log2_mic:               float
    mic_mg_l:               float
    interpretation:         str    # "susceptible" | "intermediate" | "resistant"
    eucast_breakpoint_mg_l: float  = EUCAST_R
    input_echo:             dict


# ---------------------------------------------------------------------------
# Feature vector builder
# ---------------------------------------------------------------------------

def _build_feature_vector(req: PredictionRequest) -> pd.DataFrame:
    row = {f: 0 for f in _feature_names}

    row["year"]           = req.year
    row["gender_male"]    = 1 if req.sex.lower() == "male" else 0
    row["age_paediatric"] = 1 if req.age_group.lower() == "paediatric" else 0
    row["age_elderly"]    = 1 if req.age_group.lower() == "elderly" else 0

    # Military proxy: wound specimen + male + adult
    row["military_proxy"] = int(
        req.specimen_type.lower() == "wound"
        and req.sex.lower() == "male"
        and req.age_group.lower() == "adult"
    )

    # Specimen OHE (reference = "other")
    spec_col = f"spec_{req.specimen_type.lower()}"
    if spec_col in row:
        row[spec_col] = 1

    # Country OHE — "Argentina" is the reference (first alphabetically, drop_first=True)
    ctry_col = f"ctry_{req.country}"
    if ctry_col in row:
        row[ctry_col] = 1

    # Gene flags
    row["KPC_pos"] = int(req.kpc_pos)
    row["NDM_pos"] = int(req.ndm_pos)
    row["OXA_pos"] = int(req.oxa_pos)
    row["VIM_pos"] = int(req.vim_pos)
    row["IMP_pos"] = int(req.imp_pos)
    row["GES_pos"] = int(req.ges_pos)

    # Censoring: is_censored is unknown for a new isolate; set 0 (not censored = exact MIC)
    row["is_censored"] = 0
    row["pct_censored_year"] = _censoring_lookup.get(req.year, 0.88)

    return pd.DataFrame([row])[_feature_names]


def _interpret(log2_mic: float) -> str:
    mic = 2 ** log2_mic
    if mic > EUCAST_R:
        return "resistant"
    if mic > EUCAST_R / 2:
        return "intermediate"
    return "susceptible"


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health")
def health():
    return {
        "status": "ok",
        "model_loaded": _model is not None,
        "features": len(_feature_names),
        "trend_years": len(_mic90_trend),
        "countries": len(_country_stats),
    }


@app.get("/api/trend/mic90")
def trend_mic90(source: Optional[str] = None):
    """
    MIC90 by year: actual (2004-2022) + model predictions (2019-2022) + forecast (2023-2026).
    Optional ?source=train_actual|test_actual_and_predicted|forecast_extrapolated to filter.
    """
    data = _mic90_trend
    if source:
        data = [r for r in data if r.get("source") == source]
    return {"data": data, "eucast_r_mg_l": EUCAST_R}


@app.get("/api/country-stats")
def country_stats(min_n: int = 10, sort_by: str = "pct_resistant"):
    """Resistance rate and MIC90 by country (test period 2019-2022)."""
    data = [r for r in _country_stats if r["n"] >= min_n]
    if sort_by in ("pct_resistant", "mic90_actual", "n"):
        data = sorted(data, key=lambda r: r.get(sort_by, 0), reverse=True)
    return {"data": data, "period": "2019-2022", "eucast_r_mg_l": EUCAST_R}


@app.get("/api/features/importance")
def feature_importance():
    """Top 20 SHAP features from the tuned XGBoost model."""
    return {
        "data": _shap_importance,
        "note": (
            "is_censored is a data-structure artifact (censored observations are "
            "structurally at the MIC floor), not a biological predictor."
        ),
    }


@app.post("/api/predict", response_model=PredictionResponse)
def predict(req: PredictionRequest):
    """
    Predict MIC for a single isolate given year, country, demographics, and gene flags.

    Note: this is a regression model trained on ATLAS 2004-2018. Predictions outside
    this distribution (e.g. novel countries, post-2022) carry higher uncertainty.
    """
    if _model is None:
        raise HTTPException(status_code=503, detail="Model not loaded")

    # Validate country — warn but don't reject (unknown country → all ctry_* = 0)
    known_countries = [f.replace("ctry_", "") for f in _feature_names if f.startswith("ctry_")]
    if req.country not in known_countries and req.country != "Argentina":
        # Argentina is the reference (dropped in OHE) — still valid
        pass  # unknown country → reference country behaviour

    X = _build_feature_vector(req)
    log2_pred = float(_model.predict(X)[0])
    mic_pred  = float(2 ** log2_pred)

    return PredictionResponse(
        log2_mic        = round(log2_pred, 4),
        mic_mg_l        = round(mic_pred, 4),
        interpretation  = _interpret(log2_pred),
        input_echo      = req.model_dump(),
    )


@app.get("/api/countries")
def list_countries():
    """List all countries known to the model."""
    known = [f.replace("ctry_", "") for f in _feature_names if f.startswith("ctry_")]
    known = sorted(["Argentina"] + known)  # add reference country back
    return {"countries": known, "n": len(known)}
